### PR TITLE
Sync branch from original repo

### PR DESCRIPTION
**Pull request by bitsapien**

### CODE REVIEW

**Comment by sorah** [comment]
Wait. What are you doing?

**Comment by bitsapien** [comment]
Sorry ! Wrong place !

**Comment by sorah** [comment]
I didn't notice about https://rubygems.org/gems/acmesmith-ruby-client, this is legally okay but personally I don't like this -- using same name and almost same source code makes confusion to users. I'll release a new version including #20 soon, could you update your gem to include only a dependency to the new version and stop maintaining a fork? Otherwise, could you tell me why the fork needed?

**Comment by sorah** [comment]
Addition. Distributing same code without my name is not permitted on licence AFAIK.  https://rubygems.org/gems/acmesmith-ruby-client/versions/0.7.5

**Comment by bitsapien** [comment]
I needed the fork to continue working on my case. I'll take down the one on `rubygems` once your updated version is up. I won't need the fork hereafter.

**Comment by sorah** [comment]
👌  Please yank old versions, as they're not permitted.

FYI bundler has `git:` and `ref:` specification to use the specific repo and branch, in most case you don't have to release to rubygems.org.

**Comment by bitsapien** [comment]
Thanks 👍

**Comment by sorah** [comment]
Released v0.7.0.beta1. Could you proceed replacing fork gem with a single dep to `acmesmith > 0.7.0.beta1` and yank the old versions?

**Comment by bitsapien** [comment]
I won't need `acmesmith-ruby-client` anymore. I was planning to yank the gem altogether. Is that fine ?

**Comment by sorah** [comment]
Fine.

**Pull request closed without merging**
